### ISSUE TITLE
Slime slabs not working properly

### ISSUE THREAD

**Issue by traincrisis** [chyzman/chyzyLogistics#1]
The slime slabs do not have those piston sticky properties unlike normal slime blocks. They do not connect blocks and function like regular slabs. Tested in 1.20.1 fabric.

**Comment by Dragon-Seeker** [comment]
A log if the given minecraft instance would be great and any modpack to such was used for this.

**Comment by Dragon-Seeker** [comment]
Should be fixed in the latest release
